---
  :address:              'smtp.gmail.com',    
  :port:                 587,    
  :domain:               'linehive.com',    
  :user_name:            'team@linehive.com',    
  :password:             'asdfer123',   
  :authentication:       :plain,    
  :enable_starttls_auto: true
